### ISSUE TITLE
About the TarGuess-II algorithm

### ISSUE THREAD

**Issue by echoes-maker** [CSSLabNKU/TarGuess-I#1]
I am a graduate student and am interested in password guessing and online password guessing. The work of Targuess has great influence in this field, and I really want to know more about it. If it is convenient, could you please provide the code of targuess-II? Thank you！

**Comment by CSSLabNKU** [comment]
Thank you very much for your interest in TarGuess and for your kind words about its influence in the field of password guessing and online password guessing.

We appreciate your enthusiasm and support. However, we regret to inform you that the algorithm for TarGuess-II has been transferred under intellectual property rights, and thus, we are unable to provide the code for it.

Thank you for your understanding. Please feel free to reach out if you have any further questions or need more information on our other works.

Best regards,
Crypto and System Lab in Nankai University.
